### ISSUE TITLE
Working directory is not a recognisable Ghost installation.

### ISSUE THREAD

**Issue by DanHakimi** [paladini/ghost-on-github-pages#20]

**Comment by paladini** [comment]
Thank you for reporting this (duplicate of #15 / #21).

**Fixed in:**
- **Version 3.0**: https://github.com/paladini/ghost-on-github-pages/releases/latest
- **Classic v2.0.2**: https://github.com/paladini/ghost-on-github-pages/releases/tag/v2.0.2

See comments on #21 for details. We appreciate the report.
